"""
Django settings for mariupol_portal project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import pymysql

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Для деплоя нужно указать домены в CSRF_TRUSTED_ORIGINS, например: https://yourdomain.com,https://www.yourdomain.com
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS').split(',') # Для деплоя убрать комент

# Логирование отключено, чтобы не создавать лишних файлов в продакшене
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
}

# Сессия живёт 1 час (3600 секунд) с момента последнего запроса
SESSION_COOKIE_AGE = 3600

# Сессия удаляется при закрытии браузера (если True, то SESSION_COOKIE_AGE игнорируется)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # оставляем как есть, чтобы работал возраст

# Безопасность: cookie доступна только по HTTPS (для продакшена)
SESSION_COOKIE_SECURE = True   # включите при использовании HTTPS

# Защита от JavaScript-кражи cookie
SESSION_COOKIE_HTTPONLY = True

# Application definition

# Установка драйвера PyMySQL для MySQL
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reviews',
    'simplemathcaptcha',
]

# Middleware для обеспечения безопасности, управления сессиями, аутентификацией и обслуживания статических файлов
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # для обеспечения безопасности в продакшене
    'whitenoise.middleware.WhiteNoiseMiddleware', # для обслуживания статических файлов в продакшене
    'django.contrib.sessions.middleware.SessionMiddleware', # для управления сессиями
    'django.middleware.common.CommonMiddleware', # для обработки общих задач, таких как редиректы и сжатие
    'django.middleware.csrf.CsrfViewMiddleware', # для защиты от CSRF-атак
    'django.contrib.auth.middleware.AuthenticationMiddleware', # для управления аутентификацией пользователей
    'django.contrib.messages.middleware.MessageMiddleware', # для управления сообщениями
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # для защиты от атак clickjacking
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' # для оптимизации статических файлов в продакшене

ROOT_URLCONF = 'mariupol_portal.urls' # для указания корневого URL-конфигурационного файла

# Настройка шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mariupol_portal.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Важно: для подключения к удалённой БД нужно установить пакет mysqlclient (pip install mysqlclient)

# Конфигурация подключения к удалённой MySQL базе данных
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Mariupol_reviews_DB',
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),   # raw-строка для спецсимволов
        'HOST': '789fa9519d3c550a74740d89.twc1.net',
        'PORT': '3306',
        'OPTIONS': {  
            'charset': 'utf8mb4',  # Кодировка utf8mb4 для поддержки всех символов Unicode, включая эмодзи          
            'init_command': "SET NAMES utf8mb4", # Инициализационная команда для установки кодировки при каждом подключении
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# В продакшене статические файлы обслуживаются через WhiteNoise, который использует STATIC_ROOT для хранения собранных статических файлов
STATIC_URL = '/static/'

# В продакшене нужно выполнить команду collectstatic, которая соберёт все статические файлы в директорию STATIC_ROOT
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
